### PR TITLE
Update idiorm.php

### PR DESCRIPTION
**Pull request by mkkeck**
Some bugfixes and PHPDoc improvements

### CODE REVIEW

**Comment by treffynnon** [comment]
It looks like just about every line has been changed in this pull request.

Also there is a feature freeze in place so pagination is a no go.

There is scant detail on what these changes achieve in your pull request
description.

So thanks for the pull request, but for these reasons this will not be
merged.

**Comment by mkkeck** [comment]
> It looks like just about every line has been changed in this pull request.
Okay, sorry, perhabs it's to deal with online editing (copy and paste form IDE to Git-Hub form)

> Also there is a feature freeze in place so pagination is a no go.
Thats bad for me ... is it planned in feature?

> There is scant detail on what these changes achieve in your pull request description.
What means it?

**Okay, but some bugs seems to be important (my IDE says):**

Undefined variable '$value' (see line #1470):
```php
 public function having_id_is($id) {
  return (is_array($this->_get_id_column_name())) ?
    $this->having($this->_get_compound_id_column_values($value)) :
    $this->having($this->_get_id_column_name(), $id);
  }
```
Correct
```php
public function having_id_is($id) {
  return (is_array($this->_get_id_column_name())) ?
    $this->having($this->_get_compound_id_column_values($id)) :
    $this->having($this->_get_id_column_name(), $id);
  }
```
In most cases using the same variable as a key or value both by the onner and outer 'foreach' loop either is an error or may result in an error in future (see line #1254):
```php
  public function where_any_is($values, $operator='=') {
    $data = array();
    $query = array("((");
    $first = true;
    foreach ($values as $item) {
      if ($first) {
        $first = false;
      } else {
        $query[] = ") OR (";
      }
      $firstsub = true;
      foreach($item as $key => $item) {
        $op = is_string($operator) ? $operator : (isset($operator[$key]) ? $operator[$key] : '=');
        if ($firstsub) {
          $firstsub = false;
        } else {
          $query[] = "AND";
        }
        $query[] = $this->_quote_identifier($key);
        $data[] = $item;
        $query[] = $op . " ?";
      }
    }
    $query[] = "))";
    return $this->where_raw(join($query, ' '), $data);
  }
```
Correct
```php
  public function where_any_is($values, $operator='=') {
    $data = array();
    $query = array("((");
    $first = true;
    foreach ($values as $value) {
      if ($first) {
        $first = false;
      } else {
        $query[] = ") OR (";
      }
      $firstsub = true;
      foreach($value as $key => $item) {
        $op = is_string($operator) ? $operator : (isset($operator[$key]) ? $operator[$key] : '=');
        if ($firstsub) {
          $firstsub = false;
        } else {
          $query[] = "AND";
        }
        $query[] = $this->_quote_identifier($key);
        $data[] = $item;
        $query[] = $op . " ?";
      }
    }
    $query[] = "))";
    return $this->where_raw(join($query, ' '), $data);
  }
```
Some other warning:
- line 1162: protected function _create_placeholders()
  missing return statement
- line 1792: public static function clear_cache()
  missing return statement
- line 1802: protected static function _cache_query_result()
  missing return statement
- line 1815: protected function _run():
  $cache_key might not have been defined (line 1837)
  missing return statement
- line 1982: public function save()
  Unused local variable $query (line 1983). The value of the variable is overwritten immediately.

**Comment by jeremy-harris** [comment]
Why don't you just extend the class if you wish to add pagination?

**Comment by mkkeck** [comment]
yeap ... :)

**Pull request closed without merging**
